name: Keep Backend Alive

on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Health Endpoint
        run: |
          curl -s https://main-api-latest.onrender.com/api/v1/health
          echo "Health check ping complete."
